# Generated by Django 5.2.5 on 2025-08-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sailors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('rank', models.CharField(max_length=50)),
                ('experience_years', models.IntegerField()),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('childern_names', models.CharField(blank=True, max_length=200, null=True)),
                ('home_location', models.CharField(blank=True, max_length=200, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
