# Generated by Django 5.2.5 on 2025-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sailor_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailor_users',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
