# Generated by Django 5.2.5 on 2025-08-20 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sailor_users_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailors',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sailors', to='api.sailor_users'),
            preserve_default=False,
        ),
    ]
