# Generated by Django 5.2.5 on 2025-08-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailor_users',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sailor_users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
